### ISSUE TITLE
Seed

### ISSUE THREAD

**Issue by ikrets** [SoMa-Project/tub_feasibility_check#13]
I have implemented setting seed in 10c871f. You can set the seed for a `/check_kinematics` service call with a service call parameter `seed`. If it is not specified, current time will be taken as a seed. Is this sufficient?

**Comment by zweistein** [comment]
Great! Please add the feature to relevant branches for MS5 deployment.

**Comment by ikrets** [comment]
It has already been added to `integration_jannis` branch.
