### ISSUE TITLE
cannot install dependency (libsolid3d-dev)

### ISSUE THREAD

**Issue by ninafiona** [SoMa-Project/tub_feasibility_check#19]
The dependency libsolid3d-dev is not installable. I therefore cannot build the submodule contact-motion-planning.

**Comment by zweistein** [comment]
I have `libsolid3-dev` installed on `Ubuntu 18.04`from my terminal history:
```
sudo apt install libsolid3-dev
sudo apt install libsolid3d-dev 
```

**Comment by ninafiona** [comment]
This step resolved my issue: 
* I build the solid3 package from source: https://github.com/dtecta/solid3


Some other issues came up, after these steps everything worked for me:
* for sub repo motion planning (as described in that readme): grep -rl 'dSINGLE' ./ | xargs sed -i 's/dSINGLE/dDOUBLE/g'
* I got at Qt4 + CGAL - Parse error at “BOOST_JOIN” - I had to edit the files usr/include/boost/type_traits/detail/has_binary_operator.hp and has_prefix_operator.hp: I had to add `#ifndef Q_MOC_RUN` and
`#endif` around the BOOST_JOIN namespace implementation 
* `#include <iostream>` in file tub_feasibility_check/src/workspace_checkers.cpp
